#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Concurrent real bandwidth test over proxy nodes with a minimum Mbps threshold."""

from __future__ import annotations

import argparse
import concurrent.futures
import importlib.util
import itertools
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parent.parent
SUB_DIR = ROOT / "sub"


def load_speedtest():
    spec = importlib.util.spec_from_file_location("speedtest", ROOT / "scripts" / "speedtest.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


def write_sorted(path: Path, nodes: List[str], header: str) -> int:
    nodes = sorted(set(nodes), key=lambda x: x.lower())
    path.write_text(header + "\n" + "\n".join(nodes) + ("\n" if nodes else ""), encoding="utf-8")
    return len(nodes)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default=str(SUB_DIR / "keep.txt"))
    parser.add_argument("--core", required=True)
    parser.add_argument("--limit", type=int, default=100)
    parser.add_argument("--min-mbps", type=float, default=100.0)
    parser.add_argument("--concurrency", type=int, default=6)
    parser.add_argument("--max-time", type=int, default=10)
    parser.add_argument("--url", default="https://speed.cloudflare.com/__down?bytes=10000000")
    args = parser.parse_args()

    speedtest = load_speedtest()
    path = Path(args.input)
    lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines()]
    nodes = [line for line in lines if line and not line.startswith("#")]
    if args.limit and len(nodes) > args.limit:
        step = len(nodes) // args.limit
        nodes = nodes[::step][: args.limit]

    counter = itertools.count(20900)
    results: List[Dict[str, object]] = []

    def test_node(node: str) -> Dict[str, object]:
        port = next(counter)
        mbps = speedtest.run_node_speed(node, args.core, port, args.url, args.max_time)
        return {"node": node, "mbps": round(mbps, 2) if mbps is not None else None}

    with concurrent.futures.ThreadPoolExecutor(max_workers=args.concurrency) as pool:
        futures = [pool.submit(test_node, node) for node in nodes]
        for idx, future in enumerate(concurrent.futures.as_completed(futures), 1):
            result = future.result()
            results.append(result)
            if result["mbps"]:
                log = f"  [{idx}/{len(nodes)}] {result['mbps']} Mbps"
            else:
                log = f"  [{idx}/{len(nodes)}] failed"
            print(log, flush=True)

    results.sort(key=lambda x: (x["mbps"] is None, -(x["mbps"] or 0)))
    (SUB_DIR / "speedtest.json").write_text(json.dumps(results, indent=2, ensure_ascii=False), encoding="utf-8")

    passed = [r for r in results if r["mbps"] is not None and float(r["mbps"]) >= args.min_mbps]
    fast_nodes = [str(r["node"]) for r in passed]
    count = write_sorted(
        SUB_DIR / "fast.txt",
        fast_nodes,
        f"# real speed filter: >= {args.min_mbps} Mbps\n# generated by scripts/speed_filter.py",
    )

    print(f"\ntested={len(results)}, passed={len(fast_nodes)}")
    print(f"kept nodes in sub/fast.txt: {count}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
